In [6]:
import pandas as pd
pd.set_option("display.max_colwidth", 100)

In [3]:
df = pd.read_csv("sample_text.csv")
df.shape

(8, 2)

In [4]:
df

text  \
0                                        Meditation and yoga can improve mental health   
1                     Fruits, whole grains and vegetables helps control blood pressure   
2                                    These are the latest fashion trends for this week   
3                                    Vibrant color jeans for male are becoming a trend   
4                                                   The concert starts at 7 PM tonight   
5                      Navaratri dandiya program at Expo center in Mumbai this october   
6                                    Exciting vacation destinations for your next trip   
7  Maldives and Srilanka are gaining popularity in terms of low budget vacation places   

  category  
0   Health  
1   Health  
2  Fashion  
3  Fashion  
4    Event  
5    Event  
6   Travel  
7   Travel

In [10]:
from sentence_transformers import SentenceTransformer

encoder = SentenceTransformer("all-mpnet-base-v2")
vectors = encoder.encode(df.text)
vectors.shape

(8, 768)

In [11]:
vectors

array([[-0.00247394,  0.03626722, -0.05290459, ..., -0.09152357,
        -0.03969999, -0.04330488],
       [-0.03357266,  0.00980516, -0.03250129, ..., -0.05165465,
         0.02245889, -0.03156183],
       [-0.01865323, -0.04051315, -0.01235387, ...,  0.00610587,
        -0.07179647,  0.02773852],
       ...,
       [-0.00066458,  0.04252128, -0.05645507, ...,  0.01315472,
        -0.03183565, -0.04357663],
       [-0.03317153,  0.03252457, -0.02484839, ...,  0.0117442 ,
         0.05747127,  0.00571023],
       [-0.00166393,  0.00413825, -0.04597083, ...,  0.02008525,
         0.05656247, -0.00161595]], dtype=float32)

In [12]:
dim = vectors.shape[1]
dim

768

In [13]:
import faiss

index = faiss.IndexFlatL2(dim)
index

<faiss.swigfaiss.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x0000014E0680E1E0> >

In [14]:
index.add(vectors)

In [48]:
search_query = "I want to buy yoga dress"

vec = encoder.encode(search_query)
vec.shape

(768,)

In [49]:
import numpy as np

svec = vec.reshape(1, -1)
svec.shape

(1, 768)

In [50]:
index.search(svec, k=2)

(array([[1.3698226, 1.3828435]], dtype=float32), array([[2, 0]], dtype=int64))

In [51]:
distances, indices = index.search(svec, k=2)

indices

array([[2, 0]], dtype=int64)

In [52]:
df.loc[indices[0]]

text category
2  These are the latest fashion trends for this week  Fashion
0      Meditation and yoga can improve mental health   Health